version: "3.8"
services:
  database:
    image: postgres
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app:delegated
      - /usr/src/app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 7000:7000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
volumes:
  postgres_data: