version: "3.8"
services:
  database:
    image: postgres
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 7000:7000
    depends_on:
      - backend
volumes:
  postgres_data: